containerPort: 80

securityContext:
  privileged: true
#  runAsUser: 1000

#
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
# LOT of unused stuff
#
#
#
#
volumes:
- name: hostroot
  hostPath:
    path: /

volumemounts:
- mountPath: /host
  name: hostroot
